### ISSUE TITLE
Restarts with project/workspace from last proper-exit

### ISSUE THREAD

**Issue by aliteralmind** [yedderson/SublimeRestart#10]
Currently, SublimeRestart restarts Sublime with the project that was open the last time Sublime was *properly* exited, via File>Exit. The project being used when SublimeRestart is called is ignored.

Is it possible to save this state before killing sublime, so it opens with the same project as when it closed?

This is a great extension! I hope you get it back on Package Control to give it a wider release.

**Comment by yedderson** [comment]
Yeah I was thinking about it, you're right. Done. :)
and you should find the extension on Package Control, it's approved for ST3.

**Comment by aliteralmind** [comment]
Sorry :(

*Every* time I hit restart in the new version, it hangs Sublime for like thirty seconds before exiting, and *never* re-opens it. I've reverted to the previous version for the time being.

Hopefully there's a better way...

Good news to see it on Package Control, though.

**Comment by aliteralmind** [comment]
Please consider proper branching/tagging. Currently, to revert back to the previous version, I have to download the broken version, then overwrite it with the working version of restart.py. Each stable release should be tagged (I think that's the way...I'm sort of new to Git) so historical versions can be downloaded more easily in the future.

**Comment by yedderson** [comment]
Too bad that didn't work as expected on Windows, I reverted the code the previous version and it's tagged as version 2.0.1. it would be better if you clone the sublime plug-ins repos when they are not on Package Control then you can update or rollback more easier using git.

**Comment by aliteralmind** [comment]
I've come up with a reasonable workaround, which unfortunately does not include SublimeRestart: ctrl+shift+w to close Sublime, and then F10 to open it, which I've assigned to it's taskbar shortcut.
