### ISSUE TITLE
ST3 exits, but doesn't restart Sublime. (& fyi: key-binding command name is "restart")

### ISSUE THREAD

**Issue by aliteralmind** [yedderson/SublimeRestart#8]
I've just installed the latest version, after seeing your "it works in ST3 now" message. The "Restart" command is in the File menu, but when you click on it, it exits Sublime, but it doesn't restart the application. The same is true when you press F5.

Also, for others, this is the key binding entry I've added to my user bindings:

`{ "keys": ["ctrl+alt+shift+f4"], "command": "restart" },`

I'm on Windows 8.1, 64-bit, Sublime build 3065.

**Comment by aliteralmind** [comment]
Unfortunately, it's not working consistently, and I can't pin down why it's happening.

The explicit path works all the time, I *believe*. The `getcwd` method only works sometimes.

    #Explicit path
    subprocess.call('taskkill /im sublime_text.exe /f & cmd /C "C:/applications/text/sublime_text_3/sublime_text.exe"', shell=True)
    #Original
    #subprocess.call('taskkill /im sublime_text.exe /f & cmd /C "'+ os.path.join(os.getcwd(), 'sublime_text.exe') + '"', shell=True)

**Comment by yedderson** [comment]
try to replace & with && and see if you get it working, I expect that to be the faulty thing, there is no reason for getcwd() to fail.

**Comment by aliteralmind** [comment]
That seems better.
